version: '3.9'

services:
  web1:
    container_name: web1
    build: .
    ports: 
      - "3000"
  web2:
    container_name: web2
    build: .
    ports: 
      - "3000"
  web3:
    container_name: web3
    build: .
    ports: 
      - "3000"
  load_balancer:
    container_name: nginx
    build: nginx/
    ports:
      - "80:80"
    links:
      - web1
      - web2
      - web3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock